%% 0326: higher temporal downsample rate, more motion
%% Set path
global QVDataDir;
filePath = mfilename('fullpath');
[sourceDir, scriptFname, ~] = fileparts(filePath);
[~, projName, ~] = fileparts(sourceDir);

% workDir = fullfile(QVDataDir, 'Real', projName);
workDir = fullfile(QVDataDir);
resultDir = fullfile('/Users/lokitparas/Desktop/IndependentStudy/QuantaTracking/Datasets & Results/0108-newton-filament-2/output_images/lokit');
mkdir(resultDir);

%% Quanta Parameters
W = 512;
H = 256;
param = struct(...
    ...% These parameters determine which frames are used in align and merge
    'alignTWSize', 40, 'alignTWNum', 10,...
    'mergeTWSize', 40, 'mergeTWNum', 10,...
    'srTWSize', 20, 'srTWNum', 10,...
    'refFrame', round(741),...
    ...% Parameters for align and merging, don't change for now
    'numLevels', 3, 'patchSizes', [16 16 8],...
    'upsampleRatios', [1 2 4], 'searchRadii', [1 4 8], 'numLKIters', 3,...
    'imgScale', 1,...
    'wienerC', 20,...
    'flowLambda', 0.01,...
    ...% Parameters for super-resolution, don't change for now
    'srScale', 2, 'combineRadius', 1,...
    'k_detail', 0.3, 'k_denoise', 1, 'D_th', 0.005, 'D_tr', 0.5, 'k_stretch', 1, 'k_shrink', 1,...
    't', 0.12, 's1', 12, 's2', 2, 'M_th', 2, 'wienerSRC', 8,...
    ...% Parameters for post-denoising
    'bm3dSigma', 0,...
    ...% Parameters for correcting hot pixels, not used for simulation
    'hpThresh', 100, 'correctDCR', false,...
    ...% Configuration, keep doRefine and deRefineSR false for now
    'doRefine', false, 'doSR', false, 'doRefineSR', false,...
    'debug', false, 'debugFlowErr', false, 'resultDir', resultDir);

doSimConventional = false;

%% Conventional Parameters
% convParam = struct('twSize', 1000, 'twNum', 20,...
%     'numLevels', 3, 'patchSizes', [16 16 8],...
%     'upsampleRatios', [1 2 4], 'searchRadii', [1 4 8],...
%     'mergeSWSize', 16, 'mergeSWStride', 8,...
%     'refFrame', 25000,...
%     'flowLambda', 20,...
%     'readNoiseSigma', 2.4, 'darkCurrent', 1, 'bitDepth', 10, 'fullWell', 10504, 'clipNegative', false,...
%     'imgScale', [],...
%     'randomSeed', 765,...
%     'wienerC', 4, 'useSpatialDenoise', false, 'wienerSpatialC', 1, 'wienerSpatialExp', 4,...
%     'debug', false, 'resultDir', resultDir);

%% Run test script
tic;
% Averaging window length 
N = 1500;
offset= 0;
while offset < (10000 - N)
    imbs = cell(1, N);
    for i = 1:N
        tempImg = imread(fullfile(workDir, sprintf('img_%d.png', offset+i)));
        imbs{i} = tempImg;
    end
    
    name = int2str(6*offset/N);

    % determines the extent of overlap between successive averaging windows
    offset = offset + N/6;

    % %  imbs = imbs(1:30:end);
%     N = numel(imbs);
%     toc;
%     fprintf('Finished reading images.\n');
    run ../../testReal_0326
end 
toc;